//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKHO.WCF.ClientLib.ukhowcfservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UKHO.WCF.ClientLib.ukhowcfservice.GetOrderRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Messages")]
    [System.SerializableAttribute()]
    public partial class GetOrderRequest : UKHO.WCF.ClientLib.ukhowcfservice.RequestBase {
        
        private int DistributorIDField;
        
        private int OrderIDField;
        
        private string OrderReferenceField;
        
        private UKHO.WCF.ClientLib.ukhowcfservice.ServiceType ProductServiceTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DistributorID {
            get {
                return this.DistributorIDField;
            }
            set {
                if ((this.DistributorIDField.Equals(value) != true)) {
                    this.DistributorIDField = value;
                    this.RaisePropertyChanged("DistributorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OrderReference {
            get {
                return this.OrderReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderReferenceField, value) != true)) {
                    this.OrderReferenceField = value;
                    this.RaisePropertyChanged("OrderReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public UKHO.WCF.ClientLib.ukhowcfservice.ServiceType ProductServiceType {
            get {
                return this.ProductServiceTypeField;
            }
            set {
                if ((this.ProductServiceTypeField.Equals(value) != true)) {
                    this.ProductServiceTypeField = value;
                    this.RaisePropertyChanged("ProductServiceType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetHoldingRequest", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Messages")]
    [System.SerializableAttribute()]
    public partial class GetHoldingRequest : UKHO.WCF.ClientLib.ukhowcfservice.RequestBase {
        
        private int DistributorIDField;
        
        private int LicenceIDField;
        
        private UKHO.WCF.ClientLib.ukhowcfservice.ServiceType ProductTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DistributorID {
            get {
                return this.DistributorIDField;
            }
            set {
                if ((this.DistributorIDField.Equals(value) != true)) {
                    this.DistributorIDField = value;
                    this.RaisePropertyChanged("DistributorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LicenceID {
            get {
                return this.LicenceIDField;
            }
            set {
                if ((this.LicenceIDField.Equals(value) != true)) {
                    this.LicenceIDField = value;
                    this.RaisePropertyChanged("LicenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public UKHO.WCF.ClientLib.ukhowcfservice.ServiceType ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((this.ProductTypeField.Equals(value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Messages")]
    [System.SerializableAttribute()]
    public partial class SubmitOrderRequest : UKHO.WCF.ClientLib.ukhowcfservice.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.Order OrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="https://enavigator.ukho.gov.uk/1.0")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADPRenewTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARCSRenewTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeliveryFromDateField;
        
        private UKHO.WCF.ClientLib.ukhowcfservice.DeliveryMethod DeliveryMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeliveryToDateField;
        
        private int DistIdField;
        
        private int LicenceIdField;
        
        private UKHO.WCF.ClientLib.ukhowcfservice.OrderItem[] OrderItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurchaseOrderNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADPRenewType {
            get {
                return this.ADPRenewTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ADPRenewTypeField, value) != true)) {
                    this.ADPRenewTypeField = value;
                    this.RaisePropertyChanged("ADPRenewType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARCSRenewType {
            get {
                return this.ARCSRenewTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ARCSRenewTypeField, value) != true)) {
                    this.ARCSRenewTypeField = value;
                    this.RaisePropertyChanged("ARCSRenewType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryAddress {
            get {
                return this.DeliveryAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryAddressField, value) != true)) {
                    this.DeliveryAddressField = value;
                    this.RaisePropertyChanged("DeliveryAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeliveryFromDate {
            get {
                return this.DeliveryFromDateField;
            }
            set {
                if ((this.DeliveryFromDateField.Equals(value) != true)) {
                    this.DeliveryFromDateField = value;
                    this.RaisePropertyChanged("DeliveryFromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public UKHO.WCF.ClientLib.ukhowcfservice.DeliveryMethod DeliveryMethod {
            get {
                return this.DeliveryMethodField;
            }
            set {
                if ((this.DeliveryMethodField.Equals(value) != true)) {
                    this.DeliveryMethodField = value;
                    this.RaisePropertyChanged("DeliveryMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeliveryToDate {
            get {
                return this.DeliveryToDateField;
            }
            set {
                if ((this.DeliveryToDateField.Equals(value) != true)) {
                    this.DeliveryToDateField = value;
                    this.RaisePropertyChanged("DeliveryToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DistId {
            get {
                return this.DistIdField;
            }
            set {
                if ((this.DistIdField.Equals(value) != true)) {
                    this.DistIdField = value;
                    this.RaisePropertyChanged("DistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LicenceId {
            get {
                return this.LicenceIdField;
            }
            set {
                if ((this.LicenceIdField.Equals(value) != true)) {
                    this.LicenceIdField = value;
                    this.RaisePropertyChanged("LicenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public UKHO.WCF.ClientLib.ukhowcfservice.OrderItem[] OrderItems {
            get {
                return this.OrderItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderItemsField, value) != true)) {
                    this.OrderItemsField = value;
                    this.RaisePropertyChanged("OrderItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseOrderNumber {
            get {
                return this.PurchaseOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseOrderNumberField, value) != true)) {
                    this.PurchaseOrderNumberField = value;
                    this.RaisePropertyChanged("PurchaseOrderNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceType", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts")]
    public enum ServiceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AVCSCharts = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARCSCharts = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaperCharts = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADP = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALRS = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDS = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TideTables = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Misc = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENP = 18,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryMethod", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts")]
    public enum DeliveryMethod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Download = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts")]
    [System.SerializableAttribute()]
    public partial class OrderItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.ProductType ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductPeriod {
            get {
                return this.ProductPeriodField;
            }
            set {
                if ((this.ProductPeriodField.Equals(value) != true)) {
                    this.ProductPeriodField = value;
                    this.RaisePropertyChanged("ProductPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.ProductType ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((this.ProductTypeField.Equals(value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts")]
    public enum ProductType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AVCSCharts = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARCSCharts = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaperCharts = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADLL = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADRS = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TotalTide = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALRS = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDS = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TideTables = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Misc = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENP = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ADRS6 = 99,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UKHO.WCF.ClientLib.ukhowcfservice.GetOrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.ProcessResult AcknowledgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.Message[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.ProcessResult Acknowledge {
            get {
                return this.AcknowledgeField;
            }
            set {
                if ((this.AcknowledgeField.Equals(value) != true)) {
                    this.AcknowledgeField = value;
                    this.RaisePropertyChanged("Acknowledge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIdField, value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.Message[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Messages")]
    [System.SerializableAttribute()]
    public partial class GetOrderResponse : UKHO.WCF.ClientLib.ukhowcfservice.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.MemoryStream DownloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.OrderStatus OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VesselNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.MemoryStream Download {
            get {
                return this.DownloadField;
            }
            set {
                if ((object.ReferenceEquals(this.DownloadField, value) != true)) {
                    this.DownloadField = value;
                    this.RaisePropertyChanged("Download");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.OrderStatus OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VesselName {
            get {
                return this.VesselNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VesselNameField, value) != true)) {
                    this.VesselNameField = value;
                    this.RaisePropertyChanged("VesselName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetHoldingResponse", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Messages")]
    [System.SerializableAttribute()]
    public partial class GetHoldingResponse : UKHO.WCF.ClientLib.ukhowcfservice.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.Holding[] HoldingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LicenceIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.Holding[] Holdings {
            get {
                return this.HoldingsField;
            }
            set {
                if ((object.ReferenceEquals(this.HoldingsField, value) != true)) {
                    this.HoldingsField = value;
                    this.RaisePropertyChanged("Holdings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LicenceID {
            get {
                return this.LicenceIDField;
            }
            set {
                if ((this.LicenceIDField.Equals(value) != true)) {
                    this.LicenceIDField = value;
                    this.RaisePropertyChanged("LicenceID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Messages")]
    [System.SerializableAttribute()]
    public partial class SubmitOrderResponse : UKHO.WCF.ClientLib.ukhowcfservice.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.OrderItemStatus[] OrderStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.OrderItemStatus[] OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusField, value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Common")]
    public enum ProcessResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts.Common")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText {
            get {
                return this.MessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTextField, value) != true)) {
                    this.MessageTextField = value;
                    this.RaisePropertyChanged("MessageText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItemStatus", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts")]
    [System.SerializableAttribute()]
    public partial class OrderItemStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.ProductType ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.OrderStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.ProductType Product {
            get {
                return this.ProductField;
            }
            set {
                if ((this.ProductField.Equals(value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.OrderStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts")]
    public enum OrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpectsShipCoApproval = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpectsDistributorApproval = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpectsUkhoApproval = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalProcessing = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FulfilmentInProgress = 32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Holding", Namespace="http://schemas.datacontract.org/2004/07/UKHO.B2B.Contracts")]
    [System.SerializableAttribute()]
    public partial class Holding : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UKHO.WCF.ClientLib.ukhowcfservice.ProductType ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UKHO.WCF.ClientLib.ukhowcfservice.ProductType ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((this.ProductTypeField.Equals(value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://enavigator.ukho.gov.uk/1.0", ConfigurationName="ukhowcfservice.IOrderingService")]
    public interface IOrderingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://enavigator.ukho.gov.uk/1.0/IOrderingService/SubmitOrder", ReplyAction="https://enavigator.ukho.gov.uk/1.0/IOrderingService/SubmitOrderResponse")]
        UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderResponse SubmitOrder(UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://enavigator.ukho.gov.uk/1.0/IOrderingService/SubmitOrder", ReplyAction="https://enavigator.ukho.gov.uk/1.0/IOrderingService/SubmitOrderResponse")]
        System.Threading.Tasks.Task<UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderResponse> SubmitOrderAsync(UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://enavigator.ukho.gov.uk/1.0/IOrderingService/GetOrder", ReplyAction="https://enavigator.ukho.gov.uk/1.0/IOrderingService/GetOrderResponse")]
        UKHO.WCF.ClientLib.ukhowcfservice.GetOrderResponse GetOrder(UKHO.WCF.ClientLib.ukhowcfservice.GetOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://enavigator.ukho.gov.uk/1.0/IOrderingService/GetOrder", ReplyAction="https://enavigator.ukho.gov.uk/1.0/IOrderingService/GetOrderResponse")]
        System.Threading.Tasks.Task<UKHO.WCF.ClientLib.ukhowcfservice.GetOrderResponse> GetOrderAsync(UKHO.WCF.ClientLib.ukhowcfservice.GetOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://enavigator.ukho.gov.uk/1.0/IOrderingService/GetHoldings", ReplyAction="https://enavigator.ukho.gov.uk/1.0/IOrderingService/GetHoldingsResponse")]
        UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingResponse GetHoldings(UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://enavigator.ukho.gov.uk/1.0/IOrderingService/GetHoldings", ReplyAction="https://enavigator.ukho.gov.uk/1.0/IOrderingService/GetHoldingsResponse")]
        System.Threading.Tasks.Task<UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingResponse> GetHoldingsAsync(UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderingServiceChannel : UKHO.WCF.ClientLib.ukhowcfservice.IOrderingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderingServiceClient : System.ServiceModel.ClientBase<UKHO.WCF.ClientLib.ukhowcfservice.IOrderingService>, UKHO.WCF.ClientLib.ukhowcfservice.IOrderingService {
        
        public OrderingServiceClient() {
        }
        
        public OrderingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderResponse SubmitOrder(UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderRequest request) {
            return base.Channel.SubmitOrder(request);
        }
        
        public System.Threading.Tasks.Task<UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderResponse> SubmitOrderAsync(UKHO.WCF.ClientLib.ukhowcfservice.SubmitOrderRequest request) {
            return base.Channel.SubmitOrderAsync(request);
        }
        
        public UKHO.WCF.ClientLib.ukhowcfservice.GetOrderResponse GetOrder(UKHO.WCF.ClientLib.ukhowcfservice.GetOrderRequest request) {
            return base.Channel.GetOrder(request);
        }
        
        public System.Threading.Tasks.Task<UKHO.WCF.ClientLib.ukhowcfservice.GetOrderResponse> GetOrderAsync(UKHO.WCF.ClientLib.ukhowcfservice.GetOrderRequest request) {
            return base.Channel.GetOrderAsync(request);
        }
        
        public UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingResponse GetHoldings(UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingRequest request) {
            return base.Channel.GetHoldings(request);
        }
        
        public System.Threading.Tasks.Task<UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingResponse> GetHoldingsAsync(UKHO.WCF.ClientLib.ukhowcfservice.GetHoldingRequest request) {
            return base.Channel.GetHoldingsAsync(request);
        }
    }
}
